### PR TITLE
Fix #538

### LINKED ISSUE #538: regression: #514 causes tunnel route churn for some RIB configurations
A regression has been identified where the RIB is stable but tunnel routing advertisements are constantly churning. The chrun goes away by reverting #514.

### PR DESCRIPTION
**Pull request by rcgoodfellow**
This PR fixes the bug described in #538.

The fix itself is the single line commit b90fabd7ce6fab43e052fa1a1a471a6824445382.

All of the other code in this PR is testing infrastructure in service of catching this kind of bug in CI. A series of traits are added that allow dpd, mgd and certain aspects of switch zones to be mocked up for testing. Mg-lower functions that previously used dropshot clients for dpd, ddm and the libnet interface directly now take trait impls. Production implementations of these trait impls simply pass calls through to dropshot clients or system interfaces. Testing implementations of these traits implement mock ups of these underlying subsystems.

A regression test has been added that captures #538 and is demonstrated in CI [here](https://github.com/oxidecomputer/maghemite/runs/49663852665).

### CODE REVIEW

File: mg-lower/src/lib.rs [hunk 1]
```diff
@@ -133,35 +147,39 @@ fn full_sync(
...
-    dpd: &DpdClient,
-    ddm: &DdmClient,
+    dpd: &impl Dpd,
+    ddm: &impl Ddm,
+    sw: &impl SwitchZone,
     rt: Arc<tokio::runtime::Handle>,
 ) -> Result<(), Error> {
     for prefix in notification.changed.iter() {
-        sync_prefix(tep, &db.loc_rib(), prefix, dpd, ddm, log, &rt)?;
+        sync_prefix(tep, &db.loc_rib(), prefix, dpd, ddm, sw, log, &rt)?;
```
Comment (taspelund) [inline mg-lower/src/lib.rs:169]: ditto here

File: mg-lower/src/platform.rs [hunk 2]
```diff
@@ -0,0 +1,727 @@
+//! This crate contains traits that decouple mg-lower from the underlying
+//! platform. This is useful for testing mg-lower while not having to
+//! have a running dpd, ddmd, or switch zone.
+//!
+//! TODO: maybe there can be lest boilerplate with Dropshot API traits?
```
Comment (taspelund) [inline mg-lower/src/platform.rs:5]: typo? `lest` vs `less`

File: mg-lower/src/platform.rs [hunk 3]
```diff
@@ -0,0 +1,727 @@
...
+/// This trait wraps the dpd methods mg-lower uses.
+pub(crate) trait Dpd {
+    async fn route_ipv4_get(
+        &self,
+        cidr: &Ipv4Net,
+    ) -> Result<
+        dpd_client::ResponseValue<
+            ::std::vec::Vec<dpd_client::types::Ipv4Route>,
+        >,
+        progenitor_client::Error<dpd_client::types::Error>,
```
Comment (taspelund) [inline mg-lower/src/platform.rs:22]: Seems like a `use dpd_client::types::*` would clean this up quite a bit

File: mg-lower/src/platform.rs [hunk 4]
```diff
@@ -0,0 +1,727 @@
...
+    >;
+}
+
+/// This trait wraps the ddmd methods mg-lower uses.
+pub(crate) trait Ddm {
+    async fn get_originated_tunnel_endpoints(
+        &self,
+    ) -> Result<
+        ddm_admin_client::ResponseValue<
+            Vec<ddm_admin_client::types::TunnelOrigin>,
```
Comment (taspelund) [inline mg-lower/src/platform.rs:117]: ditto here, but with `ddm_admin_client`.

File: mg-lower/src/test.rs [hunk 5]
```diff
@@ -0,0 +1,254 @@
...
+        };
+        let tep: Ipv6Addr = "fd00:a:b:c::d".parse().unwrap();
+
+        let mut rib = Rib::default();
+
+        test_setup(tep, &dpd, &ddm, &mut rib);
+
+        // Take down a link
+        dpd.links.lock().unwrap().get_mut(1).unwrap().link_state =
+            LinkState::Down;
```
Comment (taspelund) [inline mg-lower/src/test.rs:95]: Could we also exercise the link going back up?

Comment (rcgoodfellow) [reply mg-lower/src/test.rs]: Done

File: mg-lower/src/test.rs [hunk 6]
```diff
@@ -0,0 +1,254 @@
...
+            &dpd,
+            &ddm,
+            &sw,
+            &log,
+            &rt,
+        )
+        .expect("sync prefix run");
+
+        tx.send(ddm.tunnel_originated.lock().unwrap().len())
+            .unwrap();
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply mg-lower/src/test.rs]: This is the minimal reproducer of #538, but i've added more coverage here.

File: mg-lower/src/platform.rs [hunk 7]
```diff
@@ -0,0 +1,727 @@
...
+        > {
+            self.tunnel_originated
+                .lock()
+                .unwrap()
+                .retain(|x| !body.contains(x));
+            Ok(ddm_response_ok!(()))
+        }
+    }
+
+    /// A mock swtich zone implementation.
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply mg-lower/src/platform.rs]: Fixed

File: mg-lower/src/platform.rs [hunk 8]
```diff
@@ -0,0 +1,727 @@
...
+use oxnet::{IpNet, Ipv4Net, Ipv6Net};
+
+/// This trait wraps the dpd methods mg-lower uses.
+pub(crate) trait Dpd {
+    async fn route_ipv4_get(
+        &self,
+        cidr: &Ipv4Net,
+    ) -> Result<
+        dpd_client::ResponseValue<
+            ::std::vec::Vec<dpd_client::types::Ipv4Route>,
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply mg-lower/src/platform.rs]: Done. No reason other than this was copied from progenitor generated code.

File: mg-lower/src/lib.rs (hunk 1 above)
Comment (rcgoodfellow) [reply mg-lower/src/lib.rs]: Done

File: mg-lower/src/lib.rs [hunk 9]
```diff
@@ -133,35 +147,39 @@ fn full_sync(
     // Compute the bestpath for each prefix and synchronize the ASIC routing
     // tables with the chosen paths.
     for (prefix, _paths) in rib.iter() {
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply mg-lower/src/lib.rs:150]: Done

[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply mg-lower/src/lib.rs:150]: Done

**Comment by rcgoodfellow** [comment]
Did another lap in a4x2 and things still look good. Fed additional routes through the `ce` router and tunnel originations through ddm are stable.
