### PR TITLE
Various Fixes

### LINKED ISSUE #164: increase dropshot limits for ddm API
Noticed this when withdrawing a modest number of tunnel endpoints.

```
17:14:50.937Z ERRO slog-rs: withdraw tunnel endpoints: Error Response: status: 400 Bad Request; headers: {"content-type": "application/json", "x-request-id": "aaed8ef9-d718-4c9a-a206-18fd667e6420", "content-length": "123", "date": "Tue, 06 Feb 2024 17:14:50 GMT"}; value: Error { error_code: None, message: "request body exceeded maximum size of 1024 bytes", request_id: "aaed8ef9-d718-4c9a-a206-18fd667e6420" }
```

### LINKED ISSUE #165: Don't attempt to withdraw an empty set of tunnel endpoints
The following code will always make an API call to `ddmd`, even if there is nothing to withdraw.

https://github.com/oxidecomputer/maghemite/blob/fe0e548a950c0f39f5088392630e325b66e517c7/mg-lower/src/ddm.rs#L142-L144

### LINKED ISSUE #166: mg-lower: don't create superfluous notifier channels
This code

https://github.com/oxidecomputer/maghemite/blob/fe0e548a950c0f39f5088392630e325b66e517c7/mg-lower/src/lib.rs#L50-L54

will run every time we hit this inner loop break condition

https://github.com/oxidecomputer/maghemite/blob/fe0e548a950c0f39f5088392630e325b66e517c7/mg-lower/src/lib.rs#L85-L89

but that break condition is not related to the health of the channel itself and we're just creating superfluous channels.

This was triggered by #165 and resulted in the following in the logs

```
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
17:50:02.183Z ERRO slog-rs: failed to send notification to watcher 'mg-lower': sending on a closed channel
```

### PR DESCRIPTION
**Pull request by rcgoodfellow**
- Fixes #166 
- Fixes #165 
- Fixes #164

### CODE REVIEW

File: ddm/src/admin.rs [hunk 1]
```diff
@@ -54,6 +54,7 @@ pub fn handler(
 
     let config = ConfigDropshot {
         bind_address: sa,
+        request_body_max_bytes: 1024 * 1024 * 1024,
```
Comment (andrewjstone) [inline ddm/src/admin.rs:57]: chonky boi

**Review by andrewjstone — APPROVED** [review]
Looks good based on my reading of the issues and code!
