### PR TITLE
remove prefixes when nexthops have been exhausted

### LINKED ISSUE #308: Tunnel routes flapping on BGP session shutdown
When a BGP peer shuts down, and that peer is providing the only path to a given prefix, that prefix should be withdrawn from tunnel routes advertised on the rack underlay network.

Testing that I'm currently doing is showing that this is not working as expected. Instead of withdraws, we see a withdraw and then and advertise around a second later.

```
20:20:29.238Z INFO slog-rs: withdraw tunnel: {
        TunnelOrigin {
            overlay_prefix: V4(
                Ipv4Net {
                    addr: 0.0.0.0,
                    width: 0,
                },
            ),
            boundary_addr: fd21:ab92:6d64:93df::1,
            vni: 99,
            metric: 18446744073709551615,
        },
    }
```
```
20:20:30.436Z INFO slog-rs: advertise tunnel: {
        TunnelOrigin {
            overlay_prefix: V4(
                Ipv4Net {
                    addr: 0.0.0.0,
                    width: 0,
                },
            ),
            boundary_addr: fd21:ab92:6d64:93df::1,
            vni: 99,
            metric: 18446744073709551615,
        },
    }
```

Running `mgadm bgp status imported` shows there are no imported routes. So we should not be re-announcing here.

Interestingly, we see this for the static RIB.

```
$ mgadm static get-v4-routes
{
    "0.0.0.0/0": [],
}
```

which is problematic .... I'm guessing what is happening here is that the BGP daemon is removing the nexthop from the RIB with the session shuts down, but leaves the prefix with no nexthops and that is confusing mg-lower in terms of synchronizing tunnel routes to DDM in the sense that we have the prefix in the RIB, but there are no nexthops.

### LINKED ISSUE #310: bgp: changing peer vlan-id does not change entries in RIB
When a BGP peer config is changed to have a different VLAN id, the entries that correspond to that peer in the RIB are not changed. Changing the VLAN ID should result in a session reset, or maybe a session refresh, but a reset seems prudent for the moment.

### PR DESCRIPTION
**Pull request by rcgoodfellow**
- Fixes #308
- Fixes #310

### CODE REVIEW

File: rdb/src/db.rs [hunk 1]
```diff
@@ -575,6 +577,8 @@ impl Db {
             pcn.changed.insert(*prefix);
         }
 
+        rib.retain(|&_, paths| !paths.is_empty());
```
Comment (taspelund) [inline rdb/src/db.rs:580]: We already loop over `rib.iter_mut()` earlier in this function, so this will mean we effectively walk all prefixes in the RIB twice.

I think for simplicity and correctness sake this is fine for now, but we'll want to revisit this at a later date to optimize so this doesn't become a performance/convergence issue at high scale (like when receiving a full bgp feed).
e.g.
Only walk the rib once but consolidate conditional prefix removal into the path removal logic

**Review by taspelund — APPROVED** [review]

File: rdb/src/db.rs (hunk 1 above)
Comment (rcgoodfellow) [reply rdb/src/db.rs:580]: Let's get this captured in a follow-on issue.
